exports.SAVE_SUCCESS = 'Saved successfully.';
exports.PUBLISHED_SUCCESS = 'Published successfully.';
exports.INSERT_SUCCESS = 'Insert successfull.';
exports.INVALID_TEAMUUID = 'Invalid Team ID';
exports.INVALID_CREDENTIALS = 'Invalid credentials';
exports.FOUND_SUCCESS = 'Found successfully.';
exports.INVALID_CONFIG_ID = "Invalid Config ID";
exports.INVALID_PLAYERLEADERBOARD_ID = "Invalid Player Leaderboard ID";
exports.INVALID_CONTEST_LEADERBOARD_ID = "Invalid Contest Leaderboard ID";
exports.INVALID_USER_ID = "Invalid User ID";
exports.INVALID_NUMBER = "Enter 10 Digit Phone Number"
exports.INVALID_TEAM_ID = "Invalid Team ID"
exports.INVALID_CONFIG_NAME = "Invalid Config Name";
exports.INVALID_PLAYERLEADER_NAME = "Invalid Player Leaderboard Name";
exports.INVALID_PLAYER_ID = "Invalid Player ID";
exports.INVALID_MATCH_ID = "Invalid Match ID";
exports.INVALID_CONTEST_ID = "Invalid Contest ID";
exports.INVALID_POINTSYSTEMMAP_ID = "Invalid Point System Map ID";
exports.INVALID_POINTSYSTEMMAP_NAME = "Invalid Point System Map Name";
exports.INVALID_FANTASYTEAM_ID = "Invalid FantasyTeam ID";
exports.INVALID_FANTASYTEAMSQUAD_ID = "Invalid FantasyTeamSquad ID";
exports.NO_TEAM_FOUND = "No Team found"
exports.NO_POINTSYSTEM_FOUND = "No PointSystemMap found"
exports.NO_PLAYER_FOUND = "No Player found"
exports.NO_PLAYERLEADERBOARD_FOUND ="No PlayerLeaderboard found"
exports.NO_CONTEST_LEADERBOARD_FOUND ="No Contest Leaderboard found"
exports.NO_MATCH_FOUND = "No Match found"
exports.NO_USER_FOUND = "No User found";
exports.NO_CONFIG_FOUND = "No Config Details Found";
exports.NO_CONTEST_FOUND = "No Contest Found";
exports.NO_FANTASTYTEAM_FOUND = "No Fantasy Team Found";
exports.NO_FANTASTYTEAMSQUAD_FOUND = "No Fantasy Team Squad Found";
exports.INVLID_MATCHTIMELNE_ID = "Invalid Match Timeline ID";
exports.INVALID_INPUT= "Invalid Input";
exports.CONTEST_FULL= "Contest Full";
exports.NO_IN_PROGRESS_CONTEST_FOUND= "No In progress Contest Found";  
exports.NO_COMPLETED_CONTEST_FOUND= "No Completed Contest Found";   
exports.NO_SCHEDULED_CONTEST_FOUND= "No Scheduled Contest Found";   